### ISSUE TITLE
seems to be some sort of race condition with the socket

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/spalloc#4]
when running regular pynn scripts, it occasionally results with the below error.

Exception in thread SpallocJobController:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/os_shared/spinnaker_software/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/front_end_common_spalloc_allocator.py", line 51, in run
    state = self._job.wait_for_state_change(state)
  File "/os_shared/spinnaker_software/spalloc/spalloc/job.py", line 610, in wait_for_state_change
    new_state = self._get_state().state
  File "/os_shared/spinnaker_software/spalloc/spalloc/job.py", line 435, in _get_state
    state = self._client.get_job_state(self.id, timeout=self._timeout)
  File "/os_shared/spinnaker_software/spalloc/spalloc/protocol_client.py", line 211, in call
    self._send_json(command, timeout=timeout)
  File "/os_shared/spinnaker_software/spalloc/spalloc/protocol_client.py", line 173, in _send_json
    if self._sock.send(data) != len(data):
AttributeError: 'NoneType' object has no attribute 'send'

this seems to be because close() has been called between lines 166 and 173 are executing.

 Its likely that this needs to have a lock condition embedded into it for safety reasons to stop this error from occurring on a regular basis.

**Comment by mossblaser** [comment]
Not sure I can see anywhere in Job where the client is prodded from another thread to close the connection without a lock being held (aside from closing the socket but it only does that after shutting down the BG thread)... Puzzling...

Also, for the error to come out where it was, the self._sock.settimeout call must also have happened before _sock was knocked off...

Sorry, not much help there and afraid no time to look further into this at the moment, I hope you're able to reproduce this one reliably! (I'm currently knackered after doing a 'network exercise' all day where we built a TV station, from scratch in time to run the local news. Isn't it good to know the license fee is going towards funding my addiction to plugging hundreds of cables into things in a chaotic manner...)

**Comment by rowleya** [comment]
A hypothesis is that this is a locking issue from the SpiNNFrontEndCommon side.  Looking at:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/interface_functions/front_end_common_spalloc_allocator.py

We don't seem to do any locking on the job itself from our side, so it is possible for an issue to occur if:
1) Line 47 is called
2) close() is called (line 41)
3) Line 51 is called

I suspect we should lock against this here in any case and then see if the issue still occurs.

**Comment by alan-stokes** [comment]
Hi All, 

So alas its very intermittent, i only saw it a few times in a row, then it disappeared and then returned once a few runs after that. For a while I thought id buggered ups something with the iobuf changes but this seems to be the cause in the end.

Rowley is correct from how we use it and of a possible fix, but my view point (which can be argued if you wish) is that the low level interface should be as stable as possible, and therefore the high level stuff wouldn't need to adjust for intrinsic issues within the low level system. Otherwise every high level interface has to implement the same adjustments, which always seems odd, esp for a none obvious issue as this (and means duplicated code, which is my bane).

This means my view is that the best solution is for spalloc to lock over its socket. I have vague memories of our visualiser c code having to do the same thing for its sockets with mutex's so doesn't seem from my viewpoint a bad idea. 

This issue was more for a marker for me to do at some later point (and HBP tracking). I really want this iobuf stuff done first, but if someone wants to do this one whilst i'm in iobuf, id be grateful.

Jonathan, glad to know my TV licence fee is being used for good purposes ;-). I guess you didn't think the training on wiring the big spinnaker machine was going to become this usful so quickly. lol. I hope your enjoying the beeb. I wonder when you'll need to build a tv station from scratch in such a time frame these days, but meh.

**Comment by rowleya** [comment]
Looking again, there is a small issue in both.  SpiNNFrontEndCommon certainly shouldn't call things on the job after it has been destroyed, which is certainly possible in the current code.  The issue in spalloc is that I can quite easily make this call - worse, it might actually reconnect the socket up even though I have asked for it to be destroyed previously.  Better would be that any call made after destroy has been called would result in an error.

**Comment by mundya** [comment]
> worse, it might actually reconnect the socket up even though I have asked for it to be destroyed previously.

Is it not reasonable to still be able to talk to the server even though the *job* has been destroyed?

**Comment by rowleya** [comment]
Yes, but I am talking to the job at this point, not the server (from an interface perspective).  The job has been destroyed and I am then asking it to "wait for state", which is a mistake certainly.  It would be better for it to be an error to talk to the job at all once destroy has been called on it, rather than it reconnecting the socket, which then might be left open.

**Comment by alan-stokes** [comment]
think this has been solved in master now. reopen if false
