### ISSUE TITLE
Protocol-level race condition

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/spalloc#7]
Apparently (as found by @alan-stokes) there's a possibility for users of the client to fire off an operation such as `where_is` while there is a `wait_for_state_change` being processed, and this can result in the returned values for these two operations coming back in an unexpected order. That then makes the results go to the wrong caller somehow, which is understandably making them blow up in weird ways.

There are two ways to fix this, only one of which is needed:
1. Add correlation IDs to each message (with the server just sending the correlation ID back in its return-response) so that returns can be definitively directed to the correct caller. I'd like to _not_ do this, as the effort to identify exactly how to redirect misdirected returns is non-trivial. It'd probably involve some sort of hash map of waitable things and so on, and would be *really very brain-bending indeed*. (I've written this sort of thing before. I don't want to repeat the experience.)
2. Making the client so that it only ever uses a socket from one thread (probably by opening additional sockets behind the scenes for each thread that talks to the client). At that point, there's more system resource usage but it means that we can greatly reduce the amount of locking in the client and we won't need to alter the server at all (as that effectively treats each socket as needing to be parallel with the others just fine).

I recommend option 2. I really _really_ **really** recommend option 2.

**Comment by rowleya** [comment]
One socket per thread looks like a winner - especially as it doesn't seem to care that you have more than one socket per client.

**Comment by alan-stokes** [comment]
so each message request would be a dedicated thread? Assuming so, then im all for it.

**Comment by dkfellows** [comment]
It's not so much that each request is a dedicated thread, so much as each thread (that's around for any reason) gets its own socket. Since the pseudo-JSON-RPC requests wait until there's a response (enqueueing any notifications that occur while waiting) it means that there's no way for one request to slipstream past another unexpectedly (which was the cause of the bug) since those other potentially-problematic requests would only occur in other threads and hence other connections, and so can't actually interfere.

It's one of the standard ways of solving this sort of thing. Another is the correlation-ID stuff, which lets you multiplex on a single connection, but which makes clients evilly complex. (It also makes the server tricky, but not to the same extent.) The main downside is that it uses more sockets. If we have an actual problem with that, we have a _good_ problem since it is a problem of far too many users!
